apiVersion: v1
kind: Service
metadata:
  name: backend-starter-service
  labels:
    app: backend-starter
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app: backend-starter
