apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-starter
  labels:
    app: backend-starter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-starter
  template:
    metadata:
      labels:
        app: backend-starter
    spec:
      containers:
        - name: backend-starter
          image: backend-starter:latest
          imagePullPolicy: Never
          command: ['node', '--max-old-space-size=1024']
          args: ['dist/index.js']
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-starter-config
          env:
            # Node.js Memory Settings
            - name: NODE_OPTIONS
              value: '--max-old-space-size=1024'
            # MongoDB
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: mongo-uri

            # Security
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: secret-key

            # RabbitMQ
            - name: RABBITMQ_URL
              value: 'amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: rabbitmq-password

            # Redis
            - name: REDIS_URI
              value: 'redis://redis:6379'
          resources:
            requests:
              cpu: '200m'
              memory: '512Mi'
            limits:
              cpu: '1000m'
              memory: '1Gi'
