apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-starter-config
data:
  NODE_ENV: 'production'
  PORT: '8000'
  SERVERS: 'http://localhost:8000'
  ORIGIN: '*'
  CLIENT_URL: 'http://localhost:3000'
  SERVER_URL: 'http://localhost:8000'
  SERVER_DEV_URL: '*'
  API_URL: '/api'
  S3_PROFILE_IMAGES_PATH: '/profiles'
  S3_DOCUMENTS_PATH: '/documents'
  REDIS_URL: 'redis://redis:6379'
  RABBITMQ_URL: 'amqp://user:password@rabbitmq:5672'
  JWT_SECRET: 'your-secret-key'
