apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
      nodePort: 30001
    - port: 15672
      targetPort: 15672
      name: management
      nodePort: 30002
  selector:
    app: rabbitmq
