paths:
  /api/users:
    get:
      summary: Kullanıcı listesini getirir
      tags: [User]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Sayfa numarası
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Sayfa başına kayıt sayısı
        - in: query
          name: search
          schema:
            type: string
          description: Arama terimi
      responses:
        200:
          description: Kullanıcı listesi
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

    post:
      summary: Yeni kullanıcı oluşturur
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        201:
          description: Kullanıcı oluşturuldu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /api/users/{id}:
    get:
      summary: Kullanıcı detaylarını getirir
      tags: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Kullanıcı ID
      responses:
        200:
          description: Kullanıcı detayları
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    put:
      summary: Kullanıcıyı günceller
      tags: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Kullanıcı ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        200:
          description: Kullanıcı güncellendi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    delete:
      summary: Kullanıcıyı siler
      tags: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Kullanıcı ID
      responses:
        200:
          description: Kullanıcı silindi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        role:
          type: string
        isEmailVerified:
          type: boolean
        profileImage:
          type: string
        address:
          type: string
        city:
          type: string
        country:
          type: string
        systemLanguage:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    UserCreate:
      type: object
      required:
        - email
        - firstName
        - password
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        password:
          type: string
        role:
          type: string
        profileImage:
          type: string
        address:
          type: string
        city:
          type: string
        country:
          type: string
        systemLanguage:
          type: string

    UserUpdate:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        role:
          type: string
        profileImage:
          type: string
        address:
          type: string
        city:
          type: string
        country:
          type: string
        systemLanguage:
          type: string

    Pagination:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        pages:
          type: integer
